import type { Widget } from "./agent/types";
export type Preset = {id:string;label:string;brand:string;summary:string;widget:Widget};
const ns = ["n2jw-0000000000000001","n2jw-0000000000000002","n2jw-0000000000000003"];
function make(i:number,html:string,extra:string):Widget {
 const n=ns[i];return {namespace:n,html:`<div id="${n}">${html.replaceAll(/id="([^"]+)"/g, `id="${n}-$1"`).replaceAll(/href="#([^"]+)"/g, `href="#${n}-$1"`)}</div>`,css:`#${n}{--paper:#fff;--ink:#243b30;--muted:#53665b;--line:#d9e1dc;--accent:#225d40;--soft:#f0f4f1;--font:system-ui,-apple-system,'Malgun Gothic',sans-serif;color:var(--ink);background:var(--paper);font-family:var(--font);font-size:16px;line-height:1.7;padding:clamp(24px,5vw,56px);box-sizing:border-box}#${n} *{box-sizing:border-box;min-width:0}#${n} h1,#${n} h2,#${n} h3{line-height:1.25;overflow-wrap:anywhere;margin:0 0 20px;font-style:normal}#${n} h1{font-size:clamp(36px,7vw,64px);letter-spacing:-.04em}#${n} h2{font-size:28px}#${n} p{margin:0 0 24px;max-width:65ch}#${n} section{padding:40px 0;border-bottom:1px solid var(--line)}#${n} .eyebrow{color:var(--muted);font-size:14px;letter-spacing:.12em;margin-bottom:24px}#${n} a{color:var(--accent);text-underline-offset:6px;font-weight:600;display:inline-block;padding:8px 0;white-space:nowrap}#${n} a:hover{color:var(--ink)}#${n} a:focus-visible{outline:2px solid var(--accent);outline-offset:4px}#${n} a:active{opacity:.7}#${n} .note{font-size:14px;color:var(--muted)}#${n} .row{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:24px;padding:24px 0;border-top:1px solid var(--line)}#${n} li{margin-bottom:16px}#${n} ul,#${n} ol{padding-left:24px}#${n} .intro{padding-top:24px;padding-bottom:48px}@media(max-width:480px){#${n} .row{grid-template-columns:minmax(0,1fr);gap:8px}}${extra.replaceAll("$ROOT",`#${n}`)}`,js:"",install_target:"imweb-body-code-widget",interaction_ids:[],asset_ids:[]};
}
export const presets:Preset[]=[
 {id:"cafe",label:"카페",brand:"오후의 결",summary:"메뉴와 공간을 차분하게 소개하는 카페",widget:make(0,`<section class="intro" id="cafe-hero"><p class="eyebrow">OHU COFFEE · 가상 카페</p><h1>하루 사이,<br>커피 한 잔의 여백.</h1><p>커피의 향과 느긋한 대화가 머무는 곳.<br>오후의 결이 제안하는 작은 쉼을 만나보세요.</p><a href="#cafe-menu">메뉴 살펴보기</a></section><section id="cafe-menu"><h2>취향에 맞는 한 잔</h2><div class="row"><h3>필터 커피</h3><p>천천히 내려 향의 변화를 즐기는 커피.</p></div><div class="row"><h3>밀크 커피</h3><p>커피와 우유의 부드러운 균형.</p></div></section><section id="cafe-space"><h2>잠시, 나의 속도로</h2><p>책을 읽거나 이야기를 나누는 시간. 공간 소개와 실제 사진을 더해 우리 카페만의 이야기를 완성하세요.</p></section><section id="cafe-contact"><h2>방문 전 안내</h2><p>운영시간과 위치를 확인한 뒤 방문해 주세요.</p><p class="note">가상 예시입니다. 실제 운영시간·위치·메뉴 정보는 입력이 필요합니다.</p></section>`,"")},
 {id:"academy",label:"학원",brand:"바른길 배움",summary:"학습 과정과 커리큘럼에 집중한 학원",widget:make(1,`<section class="intro" id="academy-hero"><p class="eyebrow">바른길 배움 · 가상 학원</p><h1>이해하고,<br>풀어보고,<br>내 것으로.</h1><p>배움의 과정을 차근차근 안내합니다. 수업 선택에 필요한 내용을 한눈에 확인해 보세요.</p><a href="#academy-course">학습 과정 보기</a></section><section id="academy-course"><h2>배움의 순서</h2><ol><li><h3>개념 이해</h3><p>주제의 핵심부터 차근차근 살펴봅니다.</p></li><li><h3>문제 적용</h3><p>배운 내용을 문제에 적용하며 이해를 확인합니다.</p></li><li><h3>학습 정리</h3><p>다시 살펴볼 내용을 정리합니다.</p></li></ol></section><section id="academy-guide"><h2>수업을 고르기 전에</h2><p>대상 학년, 개설 과목, 수업 시간은 실제 학원의 정보를 확인해 주세요.</p></section><section id="academy-contact"><h2>수업 상담 안내</h2><p class="note">가상 예시입니다. 상담 연락처와 수업 일정은 아직 등록되지 않았습니다.</p></section>`,`$ROOT{--ink:#203447;--accent:#23568c;--soft:#eef3f8}$ROOT .intro{background:var(--soft);padding:32px}$ROOT ol{list-style:decimal-leading-zero;padding-left:36px}`)},
 {id:"nail",label:"네일샵",brand:"온유 네일",summary:"시술 선택과 예약 안내가 명확한 네일샵",widget:make(2,`<section class="intro" id="nail-hero"><p class="eyebrow">ONYU NAIL · 가상 네일샵</p><h1>손끝에 담는<br>오늘의 취향.</h1><p>단정한 원컬러부터 나를 표현하는 디자인까지.<br>원하는 시술을 천천히 살펴보세요.</p><a href="#nail-service">시술 안내 보기</a></section><section id="nail-service"><h2>어떤 분위기를 찾나요?</h2><div class="row"><h3>원컬러</h3><p>하나의 색으로 만드는 단정한 인상.</p></div><div class="row"><h3>디자인 네일</h3><p>취향에 맞는 패턴과 포인트를 상담해 보세요.</p></div><div class="row"><h3>기본 케어</h3><p>손끝을 정돈하는 기본 관리.</p></div></section><section id="nail-before"><h2>방문 전에 알려주세요</h2><ul><li>원하는 색상과 디자인</li><li>기존 젤 제거 여부</li><li>희망하는 방문 일정</li></ul></section><section id="nail-contact"><h2>예약 안내</h2><p>시술 종류와 소요 시간은 예약 전 확인이 필요합니다.</p><p class="note">가상 예시입니다. 실제 가격·예약 링크·연락처는 입력이 필요합니다.</p></section>`,`$ROOT{--ink:#48322f;--accent:#875046;--line:#e5dcd8;--soft:#f7f1ed}$ROOT h1{font-size:clamp(36px,6vw,56px)}$ROOT .intro{border-bottom:3px solid var(--accent)}`)},
];
